# Generated by Django 5.1.3 on 2026-05-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="qr_data",
        ),
        migrations.AddField(
            model_name="student",
            name="qr_code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="Qrcode_data",
        ),
    ]
