# Generated by Django 6.0.4 on 2026-05-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_bus_feerecord_collected_by_student_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
