# Generated by Django 5.1.3 on 2026-05-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_remove_student_qr_data_student_qr_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
