# Generated by Django 5.1.3 on 2026-05-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_alter_feerecord_collected_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="total_delay",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="student",
            name="total_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
