# Generated by Django 5.1.3 on 2026-05-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_student_total_delay_student_total_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="total_delay",
        ),
        migrations.RemoveField(
            model_name="student",
            name="total_paid",
        ),
    ]
