# Generated by Django 5.1.3 on 2026-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_remove_student_total_delay_remove_student_total_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_no",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
