# Generated by Django 5.1.3 on 2026-05-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_alter_student_admission_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_no",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
